_target_: experiments.calochallenge.model.CaloChallengeCINN
in_channels: 1
shape: [45, 50, 18]
patch_shape: [3, 10, 3]

coupling_block: CaloRQSplineFrEIA
nblocks: 10
is_spatial: [False, False, False, False, False, False, False, False, False, False]
cinn_kwargs: 
  bins: 10
  min_bin_sizes: [0.01, 0.01]
  default_domain: [-4.0, 20.0, -20.0, 20.0] # (left, right, bottom, top)
  identity_tails: False
  domain_clamping: null

vit_kwargs:
  dim: 1
  condition_dim: 46
  hidden_dim: 320
  out_channels: 1
  depth: 3
  num_heads: 4
  mlp_ratio: 4.0
  attn_drop: 0
  proj_drop: 0
  pos_embedding_coords: cartesian
  learn_pos_embed: True
  causal_attn: False
  cos_attn: False
  final_conv: False
  checkpoint_grads: False
  use_torch_sdpa: False  # use xformers instead
