_target_: experiments.calochallenge.model.CaloChallengeCINN
in_channels: 1
shape: [45, 50, 18]
patch_shape: [3, 5, 2]

coupling_block: CaloRQSplineNFlows
nblocks: 6
is_spatial: [False, False, False, False, False, False]
cinn_kwargs: 
  num_bins: 10
  bounds_init: 20 # (left, right, bottom, top)

vit_kwargs:
  dim: 1
  condition_dim: 46
  out_channels: 2
  final_layer_channels: 23
  hidden_dim: 360
  depth: 2
  num_heads: 4
  mlp_ratio: 4.0
  attn_drop: 0
  proj_drop: 0
  pos_embedding_coords: 'cartesian'
  learn_pos_embed: True
  causal_attn: False
  cos_attn: False
  final_conv: False
  checkpoint_grads: False
  use_torch_sdpa: False  # use xformers instead
