_target_: experiments.calohadronic.model.CaloHadCFM
in_channels: 1
shape: [45450]
list_shape:
 - [10, 15, 15]
 - [48, 30, 30]
list_edges: [2250, 43200]
list_patch_shape: [[5, 5, 3], [3, 5, 5]]

time_distribution: uniform
trajectory: linear
odeint_kwargs:
  method: rk4
  options:
    step_size: 0.05

net:
  _target_: nn.vit.ViT
  param:
    dim: 3
    condition_dim: 66
    hidden_dim: 480
    out_channels: 1
    depth: 6
    num_heads: 6
    mlp_ratio: 4
    attn_drop: 0.0
    proj_drop: 0.0
    pos_embedding_coords: cylindrical
    temperature: 10000
    learn_pos_embed: true
    causal_attn: false
    checkpoint_grads: false
    num_patches: [[2, 3, 5], [16, 6, 6]]
    patch_dim: 75
    use_torch_sdpa: false
