_target_: experiments.calogan.model.CaloGANCFM
in_channels: 1
shape: [504]
list_shape: [[1, 96, 3], [1, 12, 12], [1, 6, 12]]
list_edges: [288, 144, 72]
list_patch_shape: [[1, 6, 1], [1, 2, 3], [1, 2, 3]]

time_distribution: uniform
trajectory: linear
odeint_kwargs:
  method: rk4
  options:
    step_size: 0.05

net:
  _target_: nn.vit.ViT
  param:
    dim: 3
    condition_dim: 4
    hidden_dim: 480
    out_channels: 1
    depth: 6
    num_heads: 6
    mlp_ratio: 4
    attn_drop: 0.0
    proj_drop: 0.0
    pos_embedding_coords: cylindrical
    temperature: 10000
    learn_pos_embed: true
    causal_attn: false
    checkpoint_grads: false
    num_patches: [[1, 16, 3], [1,6,4], [1,3,4]]
    patch_dim: 6
    use_torch_sdpa: false
