_target_: experiments.calochallenge.calochallenge_cfm.model.CaloChallengeCFM_DS1
in_channels: 1
shape: [440]
list_shape:
 - [1, 8, 5]
 - [1, 16, 10]
 - [1, 19, 10]
 - [1, 5, 5]
 - [1, 5, 5]
list_edges: [40, 160, 190, 25, 25]
patch_shape: [1, 1, 5]

time_distribution: uniform
trajectory: linear
odeint_kwargs:
  method: rk4
  options:
    step_size: 0.05

net:
  _target_: nn.vit.ViT
  param:
    dim: 3
    condition_dim: 6
    hidden_dim: 480
    out_channels: 1
    depth: 6
    num_heads: 6
    mlp_ratio: 4
    attn_drop: 0.0
    proj_drop: 0.0
    pos_embedding_coords: cylindrical
    temperature: 10000
    learn_pos_embed: true
    causal_attn: false
    checkpoint_grads: false
    num_patches: [[1, 8, 1], [1, 16, 2], [1, 19, 2], [1, 5, 1], [1, 5, 1]]
    patch_dim: 5
    use_torch_sdpa: false
