_target_: models.base_model.CFM

shape: [7]

time_distribution: uniform
trajectory: linear
odeint_kwargs:
  method: rk4
  options:
    step_size: 0.05

net:
  _target_: nn.cfm.mlp_transformer.MLPTransformer
  param:
    dims_in: 7
    dims_c: 1
    dim_embedding: 64
    nhead: 4
    num_encoder_layers: 4
    num_decoder_layers: 4
    dim_feedforward: 512
    dropout: 0.0
    activation: relu
    embeds: true
    encode_t_scale: 30
