_target_: experiments.calochallenge.model.CaloChallengeCINN
in_channels: 1
shape: [53, 1, 10]
patch_shape: [1, 1, 5]

coupling_block: CaloRQSplineNFlows
nblocks: 6
is_spatial: [False, False, False, False, False, False]
spatial_factor: [1,2,1]
cinn_kwargs: 
  num_bins: 10
  bounds_init: 17 # (left, right, bottom, top)

vit_kwargs:
  dim: 3
  x1_channels: 133
  condition_dim: 6
  out_channels: 2
  final_layer_channels: 133
  hidden_dim: 240
  depth: 3
  num_heads: 6
  mlp_ratio: 4.0
  attn_drop: 0
  proj_drop: 0
  pos_embedding_coords: 'cartesian'
  learn_pos_embed: True
  causal_attn: False
  cos_attn: False
  final_conv: False
  checkpoint_grads: False
  use_torch_sdpa: False  # use xformers instead
