_target_: experiments.calochallenge.model.CaloChallengeEnergy

shape: [45]
coupling_block: RQSplineNFlows
nblocks: 5
cinn_kwargs: 
  num_bins: 14
  bounds_init: 23 # (left, right, bottom, top)

subnet_kwargs:
  n_layers: 3
  hidden_channels: [128, 128, 128]
  dropout: 0.0
