iterations: 50000
batchsize: 128
batchsize_sample: 256

optimizer: AdamW
betas: [.9, .999]
eps: 1e-8
weight_decay: 0

lr: 1e-4
scheduler: CosineAnnealingLR
scheduler_scale: 1
cosanneal_eta_min: 0
onecycle_max_lr: 10
onecycle_pct_start: 0.2

es_patience: 1000
es_load_best_model: false

log_every_n_steps: 500
validate_every_n_steps: 4000
validate_every_n_epochs_min: null

clip_grad_norm: 1000
clip_grad_value: null
max_grad_norm: null
